name: GetDataBase
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 36 * * *'
  watch:
    types: [started]
    

jobs:
  builds:
    name: GetDataBase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7

      - name: 'Install requirements'
        run: |
          pip install -r ./requirements.txt

      - name: 'Run Bing API'
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python ./main.py

      - name: "POST to Redis"
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python ./post_to_redis.py
            
      - name: Commit files
        run: |
          git config --local user.email "admin@icodeq.com"
          git config --local user.name "zkeq"
          git add .
          git commit -m "GitHub Actions Crawler at $(date +'%Y-%m-%d %H:%M:%S')"
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main